language: android # this means the project will be built in an Android environment
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
notifications:
  email: false
android:
  components:
  - tools # will be built with latest version of Android SDK tools
  - platform-tools
  - build-tools-25.0.2 # build tools version of my project
  - android-25 # Android SDK version of my project
  # Additional components
  - extra-android-m2repository # design support library
  - extra-google-m2repository # Google Play Services
  licenses:
    - android-sdk-license-.+
    - '.+'
script:
 - ./gradlew clean build -Pbuild=dev --info #connectedCheck
after_success:
 # codacy

